### ISSUE TITLE
Applying filter to main timeline causes crash

### ISSUE THREAD

**Issue by philpem** [JGRennison/retcon#4]
If I apply a filter to my main timeline, Retcon crashes.
I receive this error in the terminal:

`
retcon: deps/rapidjson/document.h:620: rapidjson::GenericValue<Encoding, Allocator>::Member* rapidjson::GenericValue<Encoding, Allocator>::FindMember(const Ch*) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; rapidjson::GenericValue<Encoding, Allocator>::Ch = char]: Assertion ```IsObject()' failed.
Aborted
`

**Comment by JGRennison** [comment]
[test-diff.txt](https://github.com/JGRennison/retcon/files/323925/test-diff.txt)
Can you try with the attached diff applied, and if that doesn't work, can you post a stacktrace and let me know what sort of filter you're using?
Thanks for reporting the issue.

**Comment by philpem** [comment]
Failed again:
`
retcon: deps/rapidjson/document.h:620: rapidjson::GenericValue<Encoding, Allocator>::Member* rapidjson::GenericValue<Encoding, Allocator>::FindMember(const Ch*) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; rapidjson::GenericValue<Encoding, Allocator>::Ch = char]: Assertion `IsObject()' failed.
Aborted
`

I'm using a filter of this type:
`
if anyuser.sname (?i)user1
or if anyuser.sname (?i)user2
  panel add SearchResult
fi
`

Short backtrace:
`
#0  0x00007ffff7a441c7 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff7a45e2a in __GI_abort () at abort.c:89
#2  0x00007ffff7a3d0bd in __assert_fail_base (fmt=0x7ffff7b9ef78 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x55e452 "IsObject()", 
    file=file@entry=0x55e371 "deps/rapidjson/document.h", line=line@entry=620, 
    function=function@entry=0x5946a0 <_ZZN9rapidjson12GenericValueINS_4UTF8IcEENS_19MemoryPoolAllocatorINS_12CrtAllocatorEEEE10FindMemberEPKcE19__PRETTY_FUNCTION__.lto_priv.2589> "rapidjson::GenericValue<Encoding, Allocator>::Member* rapidjson::GenericValue<Encoding, Allocator>::FindMember(const Ch*) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator"...) at assert.c:92
#3  0x00007ffff7a3d172 in __GI___assert_fail (assertion=0x55e452 "IsObject()", file=0x55e371 "deps/rapidjson/document.h", line=620, 
    function=0x5946a0 <_ZZN9rapidjson12GenericValueINS_4UTF8IcEENS_19MemoryPoolAllocatorINS_12CrtAllocatorEEEE10FindMemberEPKcE19__PRETTY_FUNCTION__.lto_priv.2589> "rapidjson::GenericValue<Encoding, Allocator>::Member* rapidjson::GenericValue<Encoding, Allocator>::FindMember(const Ch*) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator"...)
    at assert.c:101
#4  0x000000000047dcfb in rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::operator[](char const*) ()
#5  0x00000000004d37f9 in bool parse_util::CheckTransJsonValue<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > const&, char const*, Handler*) [clone .constprop.1280] ()
#6  0x000000000050c06d in db_lazy_user::GetJsonStringGeneric(flagwrapper<db_lazy_user::LF>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char const*) [clone .part.54] [clone .lto_priv.1973] ()
#7  0x00000000005512f0 in bool filter_item_cond_regex::user_test<db_lazy_user*>(db_lazy_user*, filter_run_state&) [clone .constprop.6] ()
#8  0x00000000004cb3b6 in filter_item_cond_regex::test(filter_db_lazy_state&, unsigned long, filter_run_state&) ()
#9  0x00000000004c6d4f in filter_item_cond::exec(filter_db_lazy_state&, unsigned long, filter_run_state&) ()
#10 0x0000000000553259 in filter_set::DBFilterTweetIDs(filter_set, btree::btree_set<unsigned long, std::greater<unsigned long>, std::allocator<unsigned long>, 256>, bool, std::function<void (std::unique_ptr<undo::action, std::default_delete<undo::action> >)>)::{lambda(sqlite3*, bool&, dbpscache&, dbfunctionmsg_callback&)#1}::operator()(sqlite3*, bool&, dbpscache&, dbfunctionmsg_callback&) const [clone .isra.307] [clone .constprop.29] ()
#11 0x0000000000554a59 in ProcessMessage(sqlite3*, std::unique_ptr<dbsendmsg, std::default_delete<dbsendmsg> >&, bool&, dbpscache&, dbiothread*, dbconn*) [clone .constprop.63] ()
#12 0x00000000004b436b in dbiothread::Entry() ()
#13 0x00007ffff66d4ac5 in wxThreadInternal::PthreadStart(wxThread*) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-2.8.so.0
#14 0x00007ffff47906aa in start_thread (arg=0x7fffe8b3a700) at pthread_create.c:333
#15 0x00007ffff7b1613d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
`

Full backtrace:
`
#0  0x00007ffff7a441c7 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
        resultvar = 0
        pid = 16888
        selftid = 16892
#1  0x00007ffff7a45e2a in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x4, sa_sigaction = 0x4}, sa_mask = {__val = {140737097469856, 140737488350555, 140737097469936, 390885249, 140737082224640, 
              140737349545848, 5629010, 5850784, 140736885982184, 0, 140737348450284, 140737349564640, 140737349545848, 18446603336612081457, 140737347937472, 140737349530065}}, 
          sa_flags = -406130688, sa_restorer = 0x7ffff7b9ef78}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007ffff7a3d0bd in __assert_fail_base (fmt=0x7ffff7b9ef78 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x55e452 "IsObject()", 
    file=file@entry=0x55e371 "deps/rapidjson/document.h", line=line@entry=620, 
    function=function@entry=0x5946a0 <_ZZN9rapidjson12GenericValueINS_4UTF8IcEENS_19MemoryPoolAllocatorINS_12CrtAllocatorEEEE10FindMemberEPKcE19__PRETTY_FUNCTION__.lto_priv.2589> "rapidjson::GenericValue<Encoding, Allocator>::Member* rapidjson::GenericValue<Encoding, Allocator>::FindMember(const Ch*) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator"...) at assert.c:92
        str = 0x7fffdd4725c0 "\320/G\335\377\177"
        total = 4096
#3  0x00007ffff7a3d172 in __GI___assert_fail (assertion=0x55e452 "IsObject()", file=0x55e371 "deps/rapidjson/document.h", line=620, 
    function=0x5946a0 <_ZZN9rapidjson12GenericValueINS_4UTF8IcEENS_19MemoryPoolAllocatorINS_12CrtAllocatorEEEE10FindMemberEPKcE19__PRETTY_FUNCTION__.lto_priv.2589> "rapidjson::GenericValue<Encoding, Allocator>::Member* rapidjson::GenericValue<Encoding, Allocator>::FindMember(const Ch*) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator"...)
    at assert.c:101
No locals.
#4  0x000000000047dcfb in rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::operator[](char const*) ()
No symbol table info available.
#5  0x00000000004d37f9 in bool parse_util::CheckTransJsonValue<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > const&, char const*, Handler*) [clone .constprop.1280] ()
No symbol table info available.
#6  0x000000000050c06d in db_lazy_user::GetJsonStringGeneric(flagwrapper<db_lazy_user::LF>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char const*) [clone .part.54] [clone .lto_priv.1973] ()
No symbol table info available.
#7  0x00000000005512f0 in bool filter_item_cond_regex::user_test<db_lazy_user*>(db_lazy_user*, filter_run_state&) [clone .constprop.6] ()
No symbol table info available.
#8  0x00000000004cb3b6 in filter_item_cond_regex::test(filter_db_lazy_state&, unsigned long, filter_run_state&) ()
No symbol table info available.
#9  0x00000000004c6d4f in filter_item_cond::exec(filter_db_lazy_state&, unsigned long, filter_run_state&) ()
No symbol table info available.
#10 0x0000000000553259 in filter_set::DBFilterTweetIDs(filter_set, btree::btree_set<unsigned long, std::greater<unsigned long>, std::allocator<unsigned long>, 256>, bool, std::function<void (std::unique_ptr<undo::action, std::default_delete<undo::action> >)>)::{lambda(sqlite3*, bool&, dbpscache&, dbfunctionmsg_callback&)#1}::operator()(sqlite3*, bool&, dbpscache&, dbfunctionmsg_callback&) const [clone .isra.307] [clone .constprop.29] ()
No symbol table info available.
#11 0x0000000000554a59 in ProcessMessage(sqlite3*, std::unique_ptr<dbsendmsg, std::default_delete<dbsendmsg> >&, bool&, dbpscache&, dbiothread*, dbconn*) [clone .constprop.63] ()
No symbol table info available.
#12 0x00000000004b436b in dbiothread::Entry() ()
No symbol table info available.
#13 0x00007ffff66d4ac5 in wxThreadInternal::PthreadStart(wxThread*) () from /usr/lib/x86_64-linux-gnu/libwx_baseu-2.8.so.0
No symbol table info available.
#14 0x00007ffff47906aa in start_thread (arg=0x7fffe8b3a700) at pthread_create.c:333
        __res = <optimised out>
        pd = 0x7fffe8b3a700
        now = <optimised out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737097475840, -5021824762309824423, 0, 140737488343727, 140737097476544, 140737488344176, 5021854001235439705, 
                5021808315015442521}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimised out>
        pagesize_m1 = <optimised out>
        sp = <optimised out>
        freesize = <optimised out>
        __PRETTY_FUNCTION__ = "start_thread"
#15 0x00007ffff7b1613d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
`

**Comment by JGRennison** [comment]
[test-diff2.txt](https://github.com/JGRennison/retcon/files/324008/test-diff2.txt)
I was able to reproduce that on my machine as well.
This patch seems to fix it here.

**Comment by philpem** [comment]
Diff2 seems to fix it here too - thanks! :)
